import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import PageProvider from "./page-provider";
import { Root } from "@/type";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const res = await fetch(`${process.env.URL}/api/global`, { next: { revalidate: 3600 } })
  const global = await res.json() as Root;

  return (
    <html lang="ru">
      <body className="text-text">
        <PageProvider global={global}>
          <Header />
          {children}
          <Footer />
        </PageProvider>
      </body>
    </html>
  );
}
